/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health check
         * @description Returns HTTP 200 and a JSON body indicating the service is running. Suitable for use as a liveness probe.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user account
         * @description Create a new user with a unique email and secure password.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate with email and password to receive a JWT access token.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Retrieve the profile of the currently authenticated user.
         */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user repositories
         * @description Retrieve all repositories owned by the currently authenticated user.
         */
        get: operations["list_repositories_repositories_get"];
        put?: never;
        /**
         * Register a repository
         * @description Add a new repository to CodeSage AI for the current user.
         */
        post: operations["create_repository_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get repository details
         * @description Retrieve a specific repository by ID, ensuring owner authorization.
         */
        get: operations["get_repository_repositories__repository_id__get"];
        /**
         * Update repository metadata
         * @description Modify repository details if owned by the current user.
         */
        put: operations["update_repository_repositories__repository_id__put"];
        post?: never;
        /**
         * Delete a repository
         * @description Delete a repository if owned by the current user.
         */
        delete: operations["delete_repository_repositories__repository_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync repository from GitHub
         * @description Fetch public metadata from the GitHub API and persist it on the repository record.  Sets status to 'ready' on success or 'failed' on GitHub error.  The caller must be the repository owner.
         */
        post: operations["sync_repository_repositories__repository_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest repository source
         * @description Retrieve repository source archive from GitHub, scan and filter files, detect languages, calculate structural metrics, and persist the ingestion result. Caller must be the repository owner.
         */
        post: operations["ingest_repository_repositories__repository_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/ingestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get latest repository ingestion
         * @description Retrieve the most recent ingestion record and structural metrics for an owned repository.
         */
        get: operations["get_latest_ingestion_repositories__repository_id__ingestion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/ingestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repository ingestions
         * @description Retrieve all historical ingestion records for an owned repository.
         */
        get: operations["list_ingestions_repositories__repository_id__ingestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/ingestions/{ingestion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get repository ingestion by ID
         * @description Retrieve a specific ingestion record by ID for an owned repository.
         */
        get: operations["get_ingestion_by_id_repositories__repository_id__ingestions__ingestion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search repository code
         * @description Perform hybrid (semantic + keyword) retrieval over the indexed codebase of an owned repository.  Returns ranked code chunks with source-location metadata. No LLM generation is performed — this endpoint returns retrieval evidence only.
         */
        post: operations["search_repository_repositories__repository_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the repository assistant a question
         * @description Ask a RAG-grounded question about an owned, indexed repository. Creates a new conversation when conversation_id is omitted, or continues an existing one owned by the caller and scoped to this repository. Returns a defined insufficient-evidence result rather than an unsupported answer when the repository has no sufficiently relevant indexed code for the question.
         */
        post: operations["ask_assistant_repositories__repository_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repository conversations
         * @description List all assistant conversations owned by the current user for this repository, most recently active first.
         */
        get: operations["list_conversations_repositories__repository_id__conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a conversation with full message history
         * @description Retrieve one conversation and its messages in chronological order.
         */
        get: operations["get_conversation_repositories__repository_id__conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain a file, line range, or symbol
         * @description Explain a specific part of an owned, indexed repository, grounded in retrieved evidence. Returns a defined insufficient-evidence result rather than a fabricated explanation when no sufficiently relevant indexed code is found for the target.
         */
        post: operations["explain_code_repositories__repository_id__explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repositories/{repository_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review repository code and/or user-provided code
         * @description Review code from an owned, indexed repository, and/or user-provided code/diff text (untrusted input, up to 20,000 characters), for a given focus area. Returns structured findings plus a human-readable summary. When the review is purely repository-scoped (no user_code) and no sufficiently relevant indexed code is found, returns a defined insufficient-evidence result rather than a fabricated review.
         */
        post: operations["review_code_repositories__repository_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health check
         * @description Returns HTTP 200 and a JSON body indicating the service is running. Suitable for use as a liveness probe.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user account
         * @description Create a new user with a unique email and secure password.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate with email and password to receive a JWT access token.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Retrieve the profile of the currently authenticated user.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user repositories
         * @description Retrieve all repositories owned by the currently authenticated user.
         */
        get: operations["list_repositories_api_v1_repositories_get"];
        put?: never;
        /**
         * Register a repository
         * @description Add a new repository to CodeSage AI for the current user.
         */
        post: operations["create_repository_api_v1_repositories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get repository details
         * @description Retrieve a specific repository by ID, ensuring owner authorization.
         */
        get: operations["get_repository_api_v1_repositories__repository_id__get"];
        /**
         * Update repository metadata
         * @description Modify repository details if owned by the current user.
         */
        put: operations["update_repository_api_v1_repositories__repository_id__put"];
        post?: never;
        /**
         * Delete a repository
         * @description Delete a repository if owned by the current user.
         */
        delete: operations["delete_repository_api_v1_repositories__repository_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync repository from GitHub
         * @description Fetch public metadata from the GitHub API and persist it on the repository record.  Sets status to 'ready' on success or 'failed' on GitHub error.  The caller must be the repository owner.
         */
        post: operations["sync_repository_api_v1_repositories__repository_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest repository source
         * @description Retrieve repository source archive from GitHub, scan and filter files, detect languages, calculate structural metrics, and persist the ingestion result. Caller must be the repository owner.
         */
        post: operations["ingest_repository_api_v1_repositories__repository_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/ingestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get latest repository ingestion
         * @description Retrieve the most recent ingestion record and structural metrics for an owned repository.
         */
        get: operations["get_latest_ingestion_api_v1_repositories__repository_id__ingestion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/ingestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repository ingestions
         * @description Retrieve all historical ingestion records for an owned repository.
         */
        get: operations["list_ingestions_api_v1_repositories__repository_id__ingestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/ingestions/{ingestion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get repository ingestion by ID
         * @description Retrieve a specific ingestion record by ID for an owned repository.
         */
        get: operations["get_ingestion_by_id_api_v1_repositories__repository_id__ingestions__ingestion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search repository code
         * @description Perform hybrid (semantic + keyword) retrieval over the indexed codebase of an owned repository.  Returns ranked code chunks with source-location metadata. No LLM generation is performed — this endpoint returns retrieval evidence only.
         */
        post: operations["search_repository_api_v1_repositories__repository_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the repository assistant a question
         * @description Ask a RAG-grounded question about an owned, indexed repository. Creates a new conversation when conversation_id is omitted, or continues an existing one owned by the caller and scoped to this repository. Returns a defined insufficient-evidence result rather than an unsupported answer when the repository has no sufficiently relevant indexed code for the question.
         */
        post: operations["ask_assistant_api_v1_repositories__repository_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List repository conversations
         * @description List all assistant conversations owned by the current user for this repository, most recently active first.
         */
        get: operations["list_conversations_api_v1_repositories__repository_id__conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a conversation with full message history
         * @description Retrieve one conversation and its messages in chronological order.
         */
        get: operations["get_conversation_api_v1_repositories__repository_id__conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain a file, line range, or symbol
         * @description Explain a specific part of an owned, indexed repository, grounded in retrieved evidence. Returns a defined insufficient-evidence result rather than a fabricated explanation when no sufficiently relevant indexed code is found for the target.
         */
        post: operations["explain_code_api_v1_repositories__repository_id__explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{repository_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review repository code and/or user-provided code
         * @description Review code from an owned, indexed repository, and/or user-provided code/diff text (untrusted input, up to 20,000 characters), for a given focus area. Returns structured findings plus a human-readable summary. When the review is purely repository-scoped (no user_code) and no sufficiently relevant indexed code is found, returns a defined insufficient-evidence result rather than a fabricated review.
         */
        post: operations["review_code_api_v1_repositories__repository_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskRequest
         * @description Payload for ``POST /repositories/{id}/ask``.
         */
        AskRequest: {
            /**
             * Message
             * @description The user's question about the repository.
             */
            message: string;
            /**
             * Conversation Id
             * @description Existing conversation to continue. Omit to start a new conversation for this repository.
             */
            conversation_id?: number | null;
        };
        /**
         * AskResponse
         * @description Response payload for ``POST /repositories/{id}/ask``.
         *
         *     ``evidence`` here is the *live* ``ChunkSearchResult`` set returned by
         *     this turn's retrieval (full chunk text, not the bounded snippet that
         *     gets persisted) — see ``ConversationService`` for the distinction.
         */
        AskResponse: {
            /** Conversation Id */
            conversation_id: number;
            /** Status */
            status: string;
            /** Answer */
            answer: string;
            /** Evidence */
            evidence?: components["schemas"]["ChunkSearchResult"][];
            /** Model */
            model?: string | null;
            /** Ingestion Id */
            ingestion_id?: number | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
        };
        /**
         * ChunkSearchResult
         * @description Individual retrieved code chunk result.
         */
        ChunkSearchResult: {
            /** Chunk Id */
            chunk_id: number;
            /** File Path */
            file_path: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Language */
            language: string | null;
            /** Chunk Type */
            chunk_type: string;
            /** Name */
            name: string | null;
            /** Chunk Text */
            chunk_text: string;
            /** Score */
            score: number;
            /** Retrieval Sources */
            retrieval_sources: string[];
        };
        /**
         * CodeSearchRequest
         * @description Payload for code search queries.
         */
        CodeSearchRequest: {
            /**
             * Query
             * @description Search query string or code symbol.
             */
            query: string;
            /**
             * Top K
             * @description Maximum number of relevant chunks to return.
             * @default 10
             */
            top_k: number;
            /**
             * @description Retrieval mode (hybrid, semantic, or keyword).
             * @default hybrid
             */
            mode: components["schemas"]["RetrievalMode"];
            /**
             * File Extensions
             * @description Filter results by exact file extensions (e.g. ['.py', '.ts']).
             */
            file_extensions?: string[] | null;
            /**
             * File Paths
             * @description Filter results by file path prefix (e.g. ['app/api/']).
             */
            file_paths?: string[] | null;
            /**
             * Min Score
             * @description Minimum normalized relevance score threshold.
             */
            min_score?: number | null;
        };
        /**
         * CodeSearchResponse
         * @description Complete response payload for a code search query.
         */
        CodeSearchResponse: {
            /** Query */
            query: string;
            /** Repository Id */
            repository_id: number;
            /** Ingestion Id */
            ingestion_id: number;
            /** Total Results */
            total_results: number;
            search_mode: components["schemas"]["RetrievalMode"];
            /** Results */
            results: components["schemas"]["ChunkSearchResult"][];
        };
        /**
         * ConversationDetailResponse
         * @description A conversation including its full, chronologically-ordered history.
         */
        ConversationDetailResponse: {
            /** Id */
            id: number;
            /** Repository Id */
            repository_id: number;
            /** Title */
            title?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages?: components["schemas"]["MessageResponse"][];
        };
        /**
         * ConversationSummaryResponse
         * @description A conversation without its full message history (list view).
         */
        ConversationSummaryResponse: {
            /** Id */
            id: number;
            /** Repository Id */
            repository_id: number;
            /** Title */
            title?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EvidenceCitation
         * @description A single soft-referenced evidence citation persisted on a Message.
         *
         *     Deliberately not a foreign key to ``code_chunks`` — see
         *     ``app.models.conversation.Message`` for why — so this shape survives
         *     repository re-indexing intact.
         */
        EvidenceCitation: {
            /** Chunk Id */
            chunk_id: number;
            /** File Path */
            file_path: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Language */
            language?: string | null;
            /** Name */
            name?: string | null;
            /** Score */
            score: number;
            /** Snippet */
            snippet: string;
        };
        /**
         * ExplainRequest
         * @description Payload for ``POST /repositories/{id}/explain``.
         */
        ExplainRequest: {
            /**
             * File Path
             * @description Repository-relative path of the file to explain.
             */
            file_path: string;
            /**
             * Start Line
             * @description Optional starting line of the target range.
             */
            start_line?: number | null;
            /**
             * End Line
             * @description Optional ending line of the target range.
             */
            end_line?: number | null;
            /**
             * Symbol
             * @description Optional function/class/symbol name to focus on.
             */
            symbol?: string | null;
            /**
             * Question
             * @description Optional specific question or focus for the explanation.
             */
            question?: string | null;
            /**
             * Conversation Id
             * @description Existing conversation to append this explanation to. Omit to get a one-off explanation with no persistence.
             */
            conversation_id?: number | null;
        };
        /**
         * ExplainResponse
         * @description Response payload for ``POST /repositories/{id}/explain``.
         */
        ExplainResponse: {
            /** Conversation Id */
            conversation_id?: number | null;
            /** Status */
            status: string;
            /** Explanation */
            explanation: string;
            /** Evidence */
            evidence?: components["schemas"]["ChunkSearchResult"][];
            /** Model */
            model?: string | null;
            /** Ingestion Id */
            ingestion_id?: number | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response model for the health-check endpoint.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /**
         * IngestionResponse
         * @description Detailed response schema for a repository ingestion run.
         */
        IngestionResponse: {
            /** Id */
            id: number;
            /** Repository Id */
            repository_id: number;
            /** Status */
            status: string;
            /** Commit Sha */
            commit_sha?: string | null;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /**
             * Total Size Bytes
             * @default 0
             */
            total_size_bytes: number;
            /**
             * Total Lines
             * @default 0
             */
            total_lines: number;
            /** Primary Language */
            primary_language?: string | null;
            /** Language Stats */
            language_stats?: {
                [key: string]: unknown;
            } | null;
            /** Directory Summary */
            directory_summary?: {
                [key: string]: number;
            } | null;
            /** File Catalog */
            file_catalog?: {
                [key: string]: unknown;
            }[] | null;
            /** Error Message */
            error_message?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * IngestionSummaryResponse
         * @description Concise response schema for listing historical ingestion runs.
         */
        IngestionSummaryResponse: {
            /** Id */
            id: number;
            /** Repository Id */
            repository_id: number;
            /** Status */
            status: string;
            /** Commit Sha */
            commit_sha?: string | null;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /**
             * Total Size Bytes
             * @default 0
             */
            total_size_bytes: number;
            /**
             * Total Lines
             * @default 0
             */
            total_lines: number;
            /** Primary Language */
            primary_language?: string | null;
            /** Language Stats */
            language_stats?: {
                [key: string]: unknown;
            } | null;
            /** Error Message */
            error_message?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MessageResponse
         * @description A single persisted conversation message.
         */
        MessageResponse: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceCitation"][] | null;
            /** Model */
            model?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RepositoryCreate
         * @description Schema for repository registration request.
         */
        RepositoryCreate: {
            /**
             * Name
             * @description Short name of the repository (e.g. 'Codesage-ai').
             */
            name: string;
            /**
             * Github Url
             * @description Full GitHub repository URL (https://github.com/owner/repo).
             */
            github_url: string;
            /**
             * Description
             * @description Optional repository description.
             */
            description?: string | null;
            /**
             * Primary Language
             * @description Primary programming language.
             */
            primary_language?: string | null;
        };
        /**
         * RepositoryResponse
         * @description Schema for repository data returned by API endpoints.
         */
        RepositoryResponse: {
            /** Id */
            id: number;
            /** Owner Id */
            owner_id: number;
            /** Name */
            name: string;
            /** Full Name */
            full_name: string;
            /** Github Url */
            github_url: string;
            /** Description */
            description: string | null;
            /** Primary Language */
            primary_language: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Github Repository Id */
            github_repository_id?: number | null;
            /** Github Owner */
            github_owner?: string | null;
            /** Default Branch */
            default_branch?: string | null;
            /** Stars */
            stars?: number | null;
            /** Forks */
            forks?: number | null;
            /** Open Issues */
            open_issues?: number | null;
            /** Github Updated At */
            github_updated_at?: string | null;
            /** Last Synced At */
            last_synced_at?: string | null;
        };
        /**
         * RepositoryStatus
         * @description Lifecycle status of a repository in CodeSage AI.
         * @enum {string}
         */
        RepositoryStatus: "pending" | "ready" | "analyzing" | "failed";
        /**
         * RepositoryUpdate
         * @description Schema for modifying repository metadata.
         */
        RepositoryUpdate: {
            /**
             * Name
             * @description Updated repository name.
             */
            name?: string | null;
            /**
             * Description
             * @description Updated description.
             */
            description?: string | null;
            /**
             * Primary Language
             * @description Updated primary programming language.
             */
            primary_language?: string | null;
            /** @description Updated processing status. */
            status?: components["schemas"]["RepositoryStatus"] | null;
        };
        /**
         * RetrievalMode
         * @description Supported retrieval search modes.
         * @enum {string}
         */
        RetrievalMode: "hybrid" | "semantic" | "keyword";
        /**
         * ReviewFindingResponse
         * @description A single structured code-review finding.
         */
        ReviewFindingResponse: {
            /** Title */
            title: string;
            /** Severity */
            severity?: string | null;
            /** Category */
            category?: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Recommendation */
            recommendation?: string | null;
            /** File Path */
            file_path?: string | null;
            /** Start Line */
            start_line?: number | null;
            /** End Line */
            end_line?: number | null;
            /** Evidence Chunk Ids */
            evidence_chunk_ids?: number[];
        };
        /**
         * ReviewFocus
         * @description Supported code-review focus areas.
         * @enum {string}
         */
        ReviewFocus: "general" | "bugs" | "security" | "maintainability" | "performance" | "style";
        /**
         * ReviewRequest
         * @description Payload for ``POST /repositories/{id}/review``.
         *
         *     Requires at least one of ``file_path`` (a repository target) or
         *     ``user_code`` (untrusted, user-supplied code/diff text) — reviewing
         *     nothing is not a valid request.
         */
        ReviewRequest: {
            /**
             * File Path
             * @description Repository-relative path of the file to review.
             */
            file_path?: string | null;
            /**
             * Symbol
             * @description Optional function/class/symbol name to focus on.
             */
            symbol?: string | null;
            /** Start Line */
            start_line?: number | null;
            /** End Line */
            end_line?: number | null;
            /**
             * @description Review focus area.
             * @default general
             */
            focus: components["schemas"]["ReviewFocus"];
            /**
             * User Code
             * @description Optional user-provided code or diff to review, treated as untrusted input. Maximum 20,000 characters.
             */
            user_code?: string | null;
            /**
             * Conversation Id
             * @description Existing conversation to append this review to. Omit to get a one-off review with no persistence.
             */
            conversation_id?: number | null;
        };
        /**
         * ReviewResponse
         * @description Response payload for ``POST /repositories/{id}/review``.
         */
        ReviewResponse: {
            /** Conversation Id */
            conversation_id?: number | null;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Findings */
            findings?: components["schemas"]["ReviewFindingResponse"][];
            /** Evidence */
            evidence?: components["schemas"]["ChunkSearchResult"][];
            /** Model */
            model?: string | null;
            /** Ingestion Id */
            ingestion_id?: number | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
        };
        /**
         * TokenResponse
         * @description Schema returned upon successful authentication containing the JWT.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description Signed JWT access token.
             */
            access_token: string;
            /**
             * Token Type
             * @description Token type (always 'bearer').
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserCreate
         * @description Schema for user registration request.
         */
        UserCreate: {
            /**
             * Email
             * Format: email
             * @description User's primary email address.
             */
            email: string;
            /**
             * Password
             * @description Plaintext password (minimum 8 characters).
             */
            password: string;
        };
        /**
         * UserLogin
         * @description Schema for user login request.
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             * @description User's registered email address.
             */
            email: string;
            /**
             * Password
             * @description User password.
             */
            password: string;
        };
        /**
         * UserResponse
         * @description Safe schema for user details returned by API endpoints.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_repositories_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"][];
                };
            };
        };
    };
    create_repository_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_repositories__repository_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_repository_repositories__repository_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_repository_repositories__repository_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_repository_repositories__repository_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_repository_repositories__repository_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_ingestion_repositories__repository_id__ingestion_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestions_repositories__repository_id__ingestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_by_id_repositories__repository_id__ingestions__ingestion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
                ingestion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_repository_repositories__repository_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_assistant_repositories__repository_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_repositories__repository_id__conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_repositories__repository_id__conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_code_repositories__repository_id__explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_code_repositories__repository_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_repositories_api_v1_repositories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"][];
                };
            };
        };
    };
    create_repository_api_v1_repositories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repository_api_v1_repositories__repository_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_repository_api_v1_repositories__repository_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RepositoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_repository_api_v1_repositories__repository_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_repository_api_v1_repositories__repository_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepositoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_repository_api_v1_repositories__repository_id__ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_ingestion_api_v1_repositories__repository_id__ingestion_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingestions_api_v1_repositories__repository_id__ingestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ingestion_by_id_api_v1_repositories__repository_id__ingestions__ingestion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
                ingestion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_repository_api_v1_repositories__repository_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodeSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_assistant_api_v1_repositories__repository_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_repositories__repository_id__conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_repositories__repository_id__conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_code_api_v1_repositories__repository_id__explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_code_api_v1_repositories__repository_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repository_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
